Repository jenkinsci/ssh-plugin, pull requests merged in 2024-11, with the labels that each got.

#26 Refresh plugin for November 2024
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: internal

#28 Format repository with Spotless
  pom.xml
  src/main/java/org/jvnet/hudson/plugins/CredentialsSSHSite.java
  src/main/java/org/jvnet/hudson/plugins/SSHBuildWrapper.java
  src/main/java/org/jvnet/hudson/plugins/SSHBuilder.java
  src/main/java/org/jvnet/hudson/plugins/VariableReplacerUtil.java
  src/test/java/org/jvnet/hudson/plugins/SSHBuildWrapperTest.java
  src/test/java/org/jvnet/hudson/plugins/VariableReplacerUtilTest.java
Labels: skip-changelog

#29 Migrate wiki documentation to GitHub
  CHANGELOG.md
  README.md
  docs/images/ssh-global-cfg.png
  docs/images/ssh-job-cfg.png
  docs/images/ssh-job-log.png
  pom.xml
Labels: documentation

#30 Revert "[JENKINS-74031] Migrate legacy checkUrl attributes in `SSHBuildWrapper/global.jelly`"
  src/main/resources/org/jvnet/hudson/plugins/SSHBuildWrapper/global.jelly
Labels: bug

#31 [JENKINS-74031] [JENKINS-74847] Fix regression created in `74031`
  src/main/resources/org/jvnet/hudson/plugins/SSHBuildWrapper/global.jelly
Labels: internal

#33 Enable CD
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: internal
